### ISSUE TITLE
remove `chkor` function from package

### ISSUE THREAD

**Issue by aylapear** [poissonconsulting/readwritesqlite#31]
R/chk.R script contains chkor function

**Comment by aylapear** [comment]
Changes out put from this where it specifies the correct name "a":
```
> chk_sqlite_conn("a") 
Error: At least one of the following conditions must be met:
* `"a"` must inherit from S4 class 'SQLiteConnection'.
* `"a"` must inherit from S3 class 'Pool'.
```

To listing it as "x" when using the vld_ functions because x_name is not passed to vld_
```
> chk_sqlite_conn("a")
Error: At least one of the following conditions must be met:
* `x` must inherit from S4 class 'SQLiteConnection'.
* `x` must inherit from S3 class 'Pool'.
```

Makes debugging a bit more confusing but not that bad, I think.

**Comment by joethorley** [comment]
Yes this is waiting on https://github.com/poissonconsulting/chk/issues/100
