### ISSUE TITLE
Failures with the dev version of RSQLite

### ISSUE THREAD

**Issue by krlmlr** [poissonconsulting/readwritesqlite#9]
Can you please run your tests with the dev version of RSQLite? I believe passing a quoted string is no longer supported, you'd need to do ``dbExistsTable(SQL("`loCaL`"))`` instead of ``dbExistsTable("`loCaL`")`` .

I'd like to release an update fairly soon. If necessary I can copy the exact error I'm seeing later.

Thanks!

**Comment by joethorley** [comment]
@krlmlr I'll do this tommorow

**Comment by joethorley** [comment]
@krlmlr on its way to CRAN
